name: rfid_flutter_core
description: Core interfaces, data classes, and enums for RFID Flutter packages. Provides the foundation for RFID reader implementations.
version: 0.0.1-beta.1
homepage:  
environment:
  sdk: '>=2.17.0 <4.0.0'

dependencies:
  meta: ^1.9.1
  # flutter:
  #   sdk: flutter

dev_dependencies:
  test: ^1.24.0
  lints: ^3.0.0
  # flutter_test:
  #   sdk: flutter
  # flutter_lints: ^3.0.0
