name: rfid_flutter_android_example
description: "Demonstrates how to use the rfid_flutter_android plugin."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  shared_preferences: ^2.2.3
  cupertino_icons: ^1.0.6
  signals: ^6.0.2
  bot_toast: ^4.1.3
  audioplayers: ^5.2.1
  package_info_plus: ^8.0.0
  rfid_flutter_android:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


# The following section is specific to Flutter packages.
flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/image/

