name: rfid_flutter_android
description: "RFID Flutter Android Plugin. Support UART, URA4 devices."
version: 0.1.0-dev.2
homepage: https://github.com/RFID-Devs/rfid_flutter_plugin/tree/main/rfid_flutter_android

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=2.10.0'

dependencies:
  flutter:
    sdk: flutter
  rfid_flutter_core: ^0.1.0-dev.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rfid.rfid_flutter_android
        pluginClass: RfidFlutterAndroidPlugin
