name: rfid_flutter_android
description: "RFID Flutter Android Plugin. Support UART, URA4 devices."
version: 0.0.1
homepage:

environment:
  sdk: '>=2.19.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  rfid_flutter_core:
    path: ../rfid_flutter_core

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rfid.rfid_flutter_android
        pluginClass: RfidFlutterAndroidPlugin
