name: Publish RFID Flutter Android
on:
  push:
    tags:
      - 'rfid_flutter_android-[0-9]+.[0-9]+.[0-9]+'
jobs:
  publish:
    permissions:
      id-token: write
    uses: dart-lang/setup-dart/.github/workflows/publish.yml@v1
    with:
      working-directory: rfid_flutter_android
